#!/bin/bash
#
# Environment variables used in the experiments.
# File run_base
#

ulimit -n 1048576

FAILED=0

function test_dir() {
	if [ ! -d "$1" ]; then
		echo "Directory not found: $1" >&2
		FAILED=1
		return 1
	fi
	return 0
}

DIR_BASE="$PWD"
[ -z "$DIR_BASE" ] && exit 1

DIR_YCSB="$DIR_BASE/../YCSB"
DIR_ROCKS="$DIR_BASE/../rocksdb"

DIR_WORK="/media/auto/work"
test_dir "$DIR_WORK"

DIR_DB_BENCH="$DIR_WORK/rocksdb"
DIR_DB_YCSB="$DIR_WORK/rocksdb_ycsb"
DIR_AT="$DIR_WORK/tmp"
test_dir "$DIR_AT"

DIR_BACKUP="/media/auto/work2"
test_dir "$DIR_BACKUP"

IO_DEVICE="nvme0n1"

DEFAULT_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ADD_PATH="/workspace/rocksdb_test/build:/workspace/YCSB/bin:/workspace/rocksdb"
DOCKER_PARAMS="-v $DIR_BASE/..:/workspace -e PATH=$DEFAULT_PATH:$ADD_PATH"
unset ADD_PATH
unset DEFAULT_PATH
